spring:
  datasource:
    username: medicine
    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/medicine_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8001
  servlet:
    context-path: /file-service